### ISSUE TITLE
Adding a duplicate identity generate wrong Exception not catched

### ISSUE THREAD

**Issue by acs** [MetricsGrimoire/sortinghat#67]
When adding a duplicated identity Sorting Hat normally generate an AlreadyExistsError exception. In this case, it does not.

```
2016-06-07 05:26:03,207 Trying to add a None identity. Ignoring it.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.4/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python3.4/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/lib/python3.4/dist-packages/MySQLdb/cursors.py", line 217, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.4/dist-packages/MySQLdb/cursors.py", line 378, in _query
    rowcount = self._do_query(q)
  File "/usr/local/lib/python3.4/dist-packages/MySQLdb/cursors.py", line 341, in _do_query
    db.query(q)
  File "/usr/local/lib/python3.4/dist-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.IntegrityError: (1062, "Duplicate entry 'c83c63183055df33c3cd046dd4ff31b87a09de75' for key 'PRIMARY'")
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "/home/bitergia/GrimoireELK/utils/grimoire/arthur.py", line 292, in enrich_backend
    ocean_backend, enrich_backend)
  File "/home/bitergia/GrimoireELK/utils/grimoire/arthur.py", line 229, in enrich_sortinghat
    new_identities, backend_name)
  File "/home/bitergia/GrimoireELK/utils/grimoire/elk/sortinghat.py", line 61, in add_identities
    identity['name'], identity['username'])
  File "/usr/local/lib/python3.4/dist-packages/sortinghat/api.py", line 165, in add_identity
    return identity_id
  File "/usr/lib/python3.4/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.4/dist-packages/sortinghat/db/database.py", line 60, in connect
```

**Comment by sduenas** [comment]
The problem was found in those identities which their values are longer than the maximum length allowed for the fields in the database (currently is set to 128). For instance, the email value of the identity to insert is this one.

```
 'Chris Peterson ext:(%2C%20Shih-Chiang%20Chien%20%3Cschien%40example.com%3E%20and%20Chris%20Jones%20%3Cjones.chris.g%40example.com.%3E)'
```
Its length is 134, 5 characters longer than the maximum allowed value. When it is inserted, the value is truncated to 128 characters. When the same identity is inserted again, the code will compare a string of 134 characters with the one inserted in the database that has 128. The comparison will say that both strings are not equal, allowing to insert the same identity twice. But because both identities have the same primary key (the same uuid) and the same truncated values, the database will raise this exception.

**Comment by sduenas** [comment]
The previous commit partially fixes the problem checking the identity identifier before inserting anything but the problem with the truncated strings persists. We need to decide what to do with truncated values, do we allow them or no? If we allow them the current UUID does not matches with the values inserted for that identity.
